### ISSUE TITLE
Order of execution of 3rd party scripts not documented

### ISSUE THREAD

**Issue by bosonnoir** [genvm/genvm#5]
The order in which 3rd party scripts are executed is unclear.
I guess that 01.host.foo is execute before 02.host.bar, but what about 01.chroot.baz??

**Comment by fhuhu** [comment]
A dedicated page was add on official website to clarify this point :  

http://www.genvm.eu/GenVM%20-%20Execution%20of%203rd%20party%20order

Thanks for your contribution
