### ISSUE TITLE
Better support for Ubuntu VMs

### ISSUE THREAD

**Issue by bosonnoir** [genvm/genvm#7]
Although generating Ubuntu VMs is supported, it requires to pass several options to the command line.
Those options are always the same, and could be provided by the script.

When passing a version name (-V version), it is not hard to know whether it is Debian or Ubuntu, and set the environment variables accordingly.

**Comment by fhuhu** [comment]
Not hard, not hard... this is a point of vue ;-) Please try  version 4df08cc in develop branch with a single line like : 

<code>
su -c "genvm -V xenial -n clt -p toor -v /tmp/clt.vmdk"
</code>

This command generate a disk image of virtual machine named "clt" in Ubuntu Xenial with root password, so GenVM detect distribution, mirror and adapt configuration :-D

Thanks for your interest
